# Generated by Django 4.1.4 on 2022-12-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='subsubcategory',
            options={'verbose_name': 'Sub Sub Category', 'verbose_name_plural': 'Sub Sub Categories'},
        ),
    ]
